config/routes.rb
Rails.application.routes.draw do
  
  root "static_pages#home"
  get  "/about",   to: "static_pages#about"
  get  "/contact", to: "static_pages#contact"
  get  "/signup",  to: "users#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }
    validates :name,  presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                      format: {with: VALID_EMAIL_REGEX},
                      uniqueness: { case_sensitive: false }

    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
  
  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def title_helper(page_title = '')
        base_title = "Shiboru"
        if page_title.empty?
            base_title
        else
            "#{page_title} | #{base_title}"
        end
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Shiboru", root_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home",   root_path %></li>
            <li><%= link_to "Log in", "#" %></li>
          </ul>
        </nav>
      </div>
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title_helper(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= title_helper(yield(:title)) %></title>
  </head>
  <body>
    <h1>Shiboru</h1>
    <p>
    自然と人をつなぐ、新しい発見の場
    <br>
    <p>
    「Shiboru」は、あなたの周りの美しい自然を写真や動画で記録し、世界中の人々と共有できる、新しい形のコミュニティです。
    </p>
    <p>
    Shiboruでできること
        <li>お気に入りの自然スポットを投稿: 美しい風景、珍しい動植物、季節の変わり目など、あなたの大切な思い出を記録しましょう。</li>
        <li>世界中の自然を探索: 世界中のユーザーが投稿した写真や動画を閲覧し、新たな発見の喜びを味わえます。</li>
        <li>コミュニティに参加: コメントやいいねで他のユーザーと交流し、自然への愛を深めましょう。</li>
     </p>
     <p>
    こんな人にオススメ
        <li>自然が好きで、美しい風景を写真に収めるのが好きな人</li>
        <li>新しい場所を探して旅に出かけるのが好きな人</li>
     </p>
     <p>
    Shiboruを使うメリット
        <li> 手軽に自然を楽しめる: スマートフォン一つで、いつでもどこでも自然と触れ合えます。</li>
        <li>自然保護に貢献: 美しい自然を守るために、情報を共有し、多くの人に自然の大切さを伝えることができます。</li>
        <li>ストレス解消: 自然に触れることは、心身に良い影響を与え、ストレスを軽減する効果が期待できます。</li>
     </p>
    Shiboruで、自然とのつながりを深め、豊かなライフスタイルを送りましょう。
    
    </p>
  </body>
</html>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact the developer about the Shiboru at the
  <a href="https://google.com">contact page</a>.
</p>

app/views/static_pages/home.html.erb
<!DOCTYPE html>
<div class="center jumbotron">
  <h1>Welcome to the Shiboru</h1>

  <h2>
    This is the home page for the
    Shiboru.
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag("oshibori.png", alt: "Oshibori image", width: "200"),
                      "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiHttc7pcCapKiqj0f_QE2RrTzzqK4Od67w066GPS5OMAz7S504BuBF-5E1ukzFQkDytz7mbVLpq-oadto_A9tyovwb1iYhIZe4iyaT3MN3-Pd2HlwcuLhLJ3Zv-xWbWGXDCi1ULP4QLuL-/s1600/oshibori.png" %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<p>This will be a signup page for new users.</p>